[package]
name = "cxx-container-testing"
version = "0.1.0"
authors = ["Tyler Swann <41113853+oraqlle@users.noreply.github.com>"]
edition = 2020
license = "MIT"
repository = "https://github.com/oraqlle/cxx-container-testing"
description = "Simple Tests of C++ standard containers"

[dependencies]
fmt = { version = "9.1.0", registry = "conan-v1" }
range-v3 = { version = "0.12.0", registry = "conan-v1" }
rapidcsv = { version = "8.75", registry = "conan-v1" }
cxxopts = { version = "3.1.1", registry = "conan-v1" }
